
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  { code: 'PTCM02312', name: 'ASIAN RIBS DE CERDO (COSTILLA CHINA)' },
  { code: 'PTCM02304', name: 'BABY BACK RIBS DE CERDO' },
  { code: 'PTCM02418', name: 'BAÑA CERDO' },
  { code: 'PTCM02406', name: 'CABEZA DE CERDO CON HUESO S/PAPADA' },
  { code: 'Carne de Cabeza', name: 'CARNE DE CABEZA CERDO' },
  { code: 'PTCM02003', name: 'CERDO DESPOSTADO' },
  { code: 'PTCM02305', name: 'CHULETA FRESCA DE CERDO' },
  { code: 'MPCM02006', name: 'COGOTE DE CERDO C/H' },
  { code: 'PTCM02425', name: 'COPA DE CERDO' },
  { code: 'PTCM02001', name: 'CORTES DE CERDO' },
  { code: 'PTCM02322', name: 'COSTILLA CARNICERA DE CERDO' },
  { code: 'PTCM02323 F', name: 'COSTILLA DE CERDO ST. LOUIS FERSCA' },
  { code: 'PTCM02323 PT', name: 'COSTILLA DE CERDO ST. LOUIS PT' },
  { code: 'PTCM02303', name: 'COSTILLA PARRILLERA DE CERDO' },
  { code: 'PTCM02423', name: 'CUERO CERDO TALLADO DE LOMO' },
  { code: 'PTCM02410', name: 'CUERO CERDO TALLADO DE PAPADA' },
  { code: 'PTCM02419', name: 'CUERO CERDO TALLADO DE TOCINETA' },
  { code: 'PTCM02427', name: 'CUERO CERDO TAPA' },
  { code: 'PTCM02402', name: 'CUERO PP DE CERDO' },
  { code: 'PTCM02421', name: 'DESPERDICIOS DE CERDO' },
  { code: 'PTCM10027', name: 'ESPALDA DE CERDO' },
  { code: 'PTCM02405', name: 'HUESO BLANCO DE CERDO' },
  { code: 'PTCM02414', name: 'HUESO ROJO (RABO) CERDO' },
  { code: 'PTCM02403', name: 'HUESO ROJO / HUESO DE CUELLO CERDO' },
  { code: 'PTCM02409', name: 'LAGARTO DE 1ERA DE CERDO' },
  { code: 'PTCM02413', name: 'LENGUA DE CERDO' },
  { code: 'PTCM02302', name: 'LOMITO DE CERDO' },
  { code: 'PTCM02301', name: 'LOMO DE CERDO' },
  { code: 'MPCM02005', name: 'LOMO DE CERDO' },
  { code: 'SIN CODIGO', name: 'MASCARA O CARETA DE CERDO' },
  { code: 'SV0201026', name: 'MINI PALETA DE CERDO' },
  { code: 'PTCM02317', name: 'MINI TOCINETA DE CERDO FRESCA' },
  { code: 'MPCM02004', name: 'PALETA DE CERDO C/H' },
  { code: 'PTCM02201', name: 'PALETA DE CERDO C/PIEL' },
  { code: 'SV0201014', name: 'PALETA DE CERDO ENTERA' },
  { code: 'PTCM02202', name: 'PALETA DE CERDO S/PIEL' },
  { code: 'PTCM02417', name: 'PAPADA CON PIEL DE CERDO' },
  { code: 'PTCM02408', name: 'PAPADA S/P DE CERDO' },
  { code: 'PTCM02401', name: 'PATICAS DE CERDO' },
  { code: 'MPCM02003', name: 'PERNIL DE CERDO C/H' },
  { code: 'PTCM02101', name: 'PERNIL DE CERDO C/HUESO C/PIEL' },
  { code: 'PTCM02102', name: 'PERNIL DE CERDO SIN PIEL' },
  { code: 'PTCM10026', name: 'PIERNA DE CERDO 96% SUPERIOR' },
  { code: 'PTCM10044', name: 'PIERNA DE CERDO 96% SUPERIOR 1*400GR' },
  { code: 'PTCM10046', name: 'PIERNA DE CERDO 96% SUPERIOR 12*800GR' },
  { code: 'PTCM10043', name: 'PIERNA DE CERDO 96% SUPERIOR 24*400GR' },
  { code: 'PTCM10116', name: 'PIERNA DE CERDO 96% SUPERIOR 5KG' },
  { code: 'PTCM10028', name: 'PIERNA DE CERDO ESTANDAR' },
  { code: 'PTCM10086', name: 'PIERNA DE CERDO ESTANDAR CON TODO' },
  { code: 'PTCM02315', name: 'PULPA DE PALETA DE CERDO ( ESPALDA 96%)' },
  { code: 'PTCM02319', name: 'PULPA DE PALETA DE CERDO 86%' },
  { code: 'PTCM02316', name: 'PULPA PERNIL DE CERDO ( PIERNA 96%)' },
  { code: 'PTCM02320', name: 'PULPA PERNIL DE CERDO 86%' },
  { code: 'PTCM02404', name: 'RECORTE #1 DE CERDO' },
  { code: 'PTCM02411', name: 'RECORTE #2 DE CERDO' },
  { code: 'PTCM02415', name: 'RECORTE #3 DE CERDO' },
  { code: 'PTCM02428', name: 'RECORTE DE COSTILLA DE CERDO' },
  { code: 'PTCM02416', name: 'RECORTE DE CUERO DE CERDO' },
  { code: 'PTCM02459', name: 'RECORTE DE CUERO PP DE CERDO' },
  { code: 'PTCM02412', name: 'RECORTE DE TETA DE CERDO' },
  { code: 'PTCM02424', name: 'RECORTE DE TOCINETA DE CERDO' },
  { code: 'PTCM02407', name: 'RECORTE ROJO DE CERDO' },
  { code: 'PTCM02307', name: 'TOCINETA FRESCA DE CERDO' },
  { code: 'PTCM02313', name: 'TOCINETA FRESCA DE CERDO SIN PIEL' },
  { code: 'PTCM02306', name: 'TOCINO DE CERDO' },
  { code: 'PTCM02318', name: 'TOCINO DE CERDO S/P' },
  { code: 'PTCM02203', name: 'PALETA DE CERDO ENTERA TIPO PICNIC' },
  { code: 'PTCM02103', name: 'PERNIL DE CERDO ENTERO TIPO PICNIC' },
  { code: 'PTCM01200', name: 'ALAS DE POLLO USO INDUSTRIAL' },
  { code: 'PTCM01400', name: 'CARAPACHO DE POLLO' },
  { code: 'PTCM01504', name: 'CARNE MOLIDA DE POLLO' },
  { code: 'PTCM01201', name: 'CHUPETA DE POLLO' },
  { code: 'PTCM01102', name: 'CHURRASCO DE MUSLO DE POLLO' },
  { code: 'PTCM01404', name: 'CUELLO DE POLLO' },
  { code: 'PTCM01503', name: 'HUESO BLANCO DE POLLO' },
  { code: 'PTCM01403', name: 'MOLLEJA DE POLLO' },
  { code: 'PTCM01100', name: 'MUSLO DE POLLO' },
  { code: 'PTCM10034', name: 'PECHUGA COCIDA DE POLLO SUPERIOR' },
  { code: 'PTCM10081', name: 'PECHUGA DE PAVO PREMIER 1 KG' },
  { code: 'PTCM10082', name: 'PECHUGA DE PAVO PREMIER 500 GR' },
  { code: 'PTCM10074', name: 'PECHUGA DE PAVO PUNTA DE MONTE 12X800GR' },
  { code: 'PTCM10095', name: 'PECHUGA DE PAVO PUNTA DE MONTE 24X400 GR' },
  { code: 'PTCM10020', name: 'PECHUGA DE POLLO PUNTA DE MONTE 12UND*800GR' },
  { code: 'PTCM10029', name: 'PECHUGA PAVO SUPERIOR' },
  { code: 'PTCM01401', name: 'PIEL DE POLLO' },
  { code: 'PTCM01500', name: 'POLLO BENEFICIADO DP FTPE' },
  { code: 'PTCM01002', name: 'POLLO BENEFICIADO GRADO A DESNUDO' },
  { code: 'PTCM01018', name: 'POLLO BENEFICIADO GRADO A EMBOLSADO C PUROLOMO' },
  { code: 'PTCM01001', name: 'POLLO BENEFICIADO GRADO A EMBOLSADO F' },
  { code: 'PTCM01017', name: 'POLLO BENEFICIADO GRADO A EMBOLSADO F PUROLOMO' },
  { code: 'PTCM01003', name: 'POLLO BENEFICIADO GRADO B' },
  { code: 'PTCM01009', name: 'POLLO BROASTER' },
  { code: 'PTCM01008', name: 'POLLO ESPECIAL TIPO INDUSTRIA' },
  { code: 'PTCM01016', name: 'POLLO MARINADO' },
  { code: 'PTCM01012', name: 'POLLO PARA RESTAURANT AS' },
  { code: 'PTCM01007', name: 'POLLO TIPO ARTUROS' },
  { code: 'PTCM01005', name: 'POLLO TIPO BRASA' },
  { code: 'PTCM01502', name: 'RECORTE ROJO DE POLLO' },
  { code: 'MPCM01178', name: 'EMULSION DE CUERO' },
  { code: 'MPCM01173', name: 'EMULSION DE TOCINO' },
  { code: 'MPCM01019', name: 'CDM DE POLLO' },
  { code: 'MPCM01040', name: 'POLLO BENEFICIADO SP BF' },
  { code: 'MPCM01043', name: 'POLLO BENEFICIADO SP C' },
  { code: 'MPCM01042', name: 'POLLO BENEFICIADO SP CH' },
  { code: 'PTCM01404', name: 'POLLO BENEFICIADO SP DD' },
  { code: 'MPCM01045', name: 'POLLO BENEFICIADO SP GL' },
  { code: 'MPCM01044', name: 'POLLO BENEFICIADO SP GP' },
  { code: 'MPCM01058', name: 'POLLO BENEFICIADO SP MU' },
  { code: 'MPCM01041', name: 'POLLO BENEFICIADO SP Z' },
  { code: 'MPCM01018', name: 'CDM (GALLINA)' },
  { code: 'PTCM02308', name: 'CHULETA DE CERDO FRESCA TIPO 1' },
  { code: 'PTCM02311', name: 'COSTILLA PARRILLERA DE CERDO TIPO 1 (AHUMADA)' },
  { code: 'PTCM10030', name: 'ESPALDA AHUMADO' },
  { code: 'PTCM02321', name: 'HUESO AHUMADO TIPO 1' },
  { code: 'PTCM02314', name: 'MINI TOCINETA DE CERDO TIPO 1' },
  { code: 'SV0201015', name: 'PALETA DE CERDO ENTERA TIPO 1' },
  { code: 'SV0201021', name: 'PECHUGA ENTERA TIPO 1' },
  { code: 'PTCM02309', name: 'TOCINETA DE CERDO FRESCA TIPO 1' },
  { code: 'PTCM02310', name: 'TOCINETA DE CERDO FRESCA TIPO 1 HM' },
  { code: 'PTCM02438', name: 'CERDO CANAL MADRE' },
  { code: 'PTCM02449', name: 'CABEZA DE MADRE PORCINA' },
  { code: 'PTCM02439', name: 'CARNE DE MADRE' },
  { code: 'PTCM02444', name: 'COSTILLAS CHINAS DE MADRE' },
  { code: 'PTCM02448', name: 'CUERO C/G MADRE' },
  { code: 'PTCM02452', name: 'DESPERDICIOS DE MADRE' },
  { code: 'PTCM02451', name: 'HUESO BLANCO DE MADRE' },
  { code: 'PTCM02445', name: 'HUESO ROJO DE MADRE' },
  { code: 'PTCM02450', name: 'LENGUA DE MADRE' },
  { code: 'PTCM02441', name: 'PAPADA S/P DE MADRE' },
  { code: 'PTCM02446', name: 'PATAS DE MADRE' },
  { code: 'PTCM02447', name: 'RABO DE MADRE' },
  { code: 'PTCM02440', name: 'RECORTE #1 DE MADRE' },
  { code: 'PTCM02443', name: 'RECORTE #2 DE MADRE' },
  { code: 'PTCM02442', name: 'RECORTE ROJO DE MADRE' },
  { code: 'MPCM03001', name: 'CACHETE DE RES' },
  { code: 'PTCM03001', name: 'CHOCOZUELA DE RES' },
  { code: 'PTCM03002', name: 'COSTILLA DE RES' },
  { code: 'PTCM03003', name: 'GANZO DE RES' },
  { code: 'PTCM03004', name: 'LAGARTO DELANTERO DE RES' },
  { code: 'PTCM03005', name: 'LAGARTO LA REINA DE RES' },
  { code: 'PTCM03006', name: 'LAGARTO TRASERO DE RES' },
  { code: 'PTCM03007', name: 'LOMITO DE RES' },
  { code: 'PTCM03008', name: 'MUCHACHO CUADRADO DE RES' },
  { code: 'PTCM03009', name: 'MUCHACHO REDONDO DE RES' },
  { code: 'PTCM03010', name: 'PALETA DE RES' },
  { code: 'PTCM03011', name: 'PECHO DE RES' },
  { code: 'PTCM03012', name: 'POLLO DE RES' },
  { code: 'PTCM03013', name: 'PULPA NEGRA DE RES' },
  { code: 'PTCM03014', name: 'PUNTA TRASERA DE RES' },
  { code: 'PTCM03015', name: 'SOLOMO ABIERTO DE RES' },
  { code: 'PTCM03016', name: 'SOLOMO DE CUERITO ANGOSTO DE RES' },
  { code: 'PTCM03017', name: 'TRASTE DE RES' },
  { code: 'PTCM17006', name: 'TENDERS DE POLLO EMPANIZADA UNDS' },
  { code: 'PTCM17003', name: 'TENDERS DE POLLO EMPANIZADO GRANEL' },
  { code: 'PTCM17005', name: 'MILANESA DE POLLO EMPANIZADA 18 B X 5 UNDS' },
  { code: 'PTCM17002', name: 'MILANESA DE POLLO EMPANIZADA GRANEL' },
  { code: 'PTCM17004', name: 'NUGGETS DE POLLO EMPANIZADO 16 B X 20 UNDS' },
  { code: 'PTCM17001', name: 'NUGGETS DE POLLO EMPANIZADO GRANEL' },
  { code: 'SV1700005', name: 'FILET DE PECHUGA DE POLLO AUTOSERVICIO TIPO M 18 B X 5 UNDS' },
  { code: 'SV1700004', name: 'FILET DE PECHUGA DE POLLO AUTOSERVICIO TIPO N 16 B X 20 UNDS' },
  { code: 'SV1700006', name: 'FILET DE PECHUGA DE POLLO AUTOSERVICIO TIPO T UNDS' },
  { code: 'SV1700009', name: 'FILET DE PECHUGA DE POLLO HB GRANEL' },
  { code: 'SV1700010', name: 'FILET DE PECHUGA DE POLLO HBA 18 B X 5 UNDS' },
  { code: 'PTCM01301', name: 'FILET DE PECHUGA DE POLLO USO INDUSTRIAL' },
  { code: 'SV1700002', name: 'FILET DE PECHUGA DE POLLO USO INDUSTRIAL TIPO M' },
  { code: 'SV1700001', name: 'FILET DE PECHUGA DE POLLO USO INDUSTRIAL TIPO N' },
  { code: 'SV1700003', name: 'FILET DE PECHUGA DE POLLO USO INDUSTRIAL TIPO T' },
  { code: 'PTCM01300', name: 'FILET INDUSTRIAL DE PECHUGA DE POLLO' },
  { code: 'SV0201020', name: 'PECHUGA ENTERA DE POLLO' },
  { code: 'SV0201018', name: 'PECHUGA ENTERA DE POLLO 12UND.' },
  { code: 'SV0201019', name: 'PECHUGA ENTERA DE POLLO 24UND.' },
  { code: 'PTCM01506', name: 'GALLINA BENEFICIADA' },
  { code: 'PTCM01508', name: 'GALLINA BENEFICIADA LIVIANA' },
  { code: 'PTCM01507', name: 'GALLINA BENEFICIADA PESADA' },
  { code: 'PTCM01505', name: 'GALLINA EMBOLSADA CONGELADA' },
  { code: 'PTCM17008', name: 'CARNE DE HAMBURGUESA 18 B X 5 UNDS' },
  { code: 'PTCM17007', name: 'CARNE DE HAMBURGUESA GRANEL' },
  { code: 'PTCM02430', name: 'CHULETA FRESCA DE CERDO AUTOSERVICIO' },
  { code: 'PTCM02432', name: 'COCHINILLO ENTERO AUTOSERVICIO' },
  { code: 'PTCM02436', name: 'COSTILLA BBR AUTOSERVICIO' },
  { code: 'PTCM02437', name: 'COSTILLA CARNICERA AUTOSERVICIO' },
  { code: 'PTCM02435', name: 'COSTILLA PARRILLERA AUTOSERVICIO' },
  { code: 'PTCM02431', name: 'LOMITO DE CERDO AUTOSERVICIO' },
  { code: 'PTCM02429', name: 'LOMO DE CERDO AUTOSERVICIO' },
  { code: 'PTCM02429medio', name: 'MEDIO LOMO DE CERDO AUTOSERVICIO*' },
  { code: 'PTCM02434', name: 'PALETA DE CERDO AUTOSERVICIO' },
  { code: 'PTCM02433', name: 'PERNIL DE CERDO AUTOSERVICIO' },
  { code: 'MPCM01155', name: 'REPROCESOS DE AVES' },
  { code: 'MPCM01154', name: 'REPROCESOS DE JAMONES' },
  { code: 'MPCM01157', name: 'REPROCESOS MORTADELA TAPARA' },
  { code: 'PTCM12001', name: 'PAPAS PRECOCIDAS COGELADAS 3/8' },
  { code: 'PTCM12004', name: 'PAPAS PRECOCIDAS COGELADAS UND 1 KG' },
  { code: 'PTCM12003', name: 'CAJAS DE PAPAS PRECOCIDAS COGELADAS 10 X 1 KG' },
  { code: 'PTCM01103', name: 'CHURRASCO DE MUSLO S/PIEL' },
  { code: 'PTCM02002', name: 'COCHINILLO ENTERO' },
  { code: 'PTCM02453', name: 'COGOTE CON HUESO' },
  { code: 'PTCM01509', name: 'DESCARTE DESPRESADO (DD)' },
  { code: 'PTCM10085', name: 'ESPALDA COCIDA 3KG CON TODO' },
  { code: 'PTCM10117', name: 'ESPALDA COCIDA CON TODO 4,5KG' },
  { code: 'SV0201027', name: 'PALETA DE CERDO ENTERA TIPO 2' },
  { code: 'SV0201029', name: 'PALETA DE CERDO TIPO 3' },
  { code: 'SV0201041', name: 'PALETA DE CERDO TIPO 3 4,5KG' },
  { code: 'PTCM02426', name: 'RIÑONADA COCIDA' },
  { code: 'PTCM02422', name: 'TRAQUEA' }
];

export const UI_COLORS = {
  bgBase: '#0B1221',
  bgCard: '#121A2D',
  primaryNeon: 'linear-gradient(135deg, #A855F7 0%, #3B82F6 100%)',
  vibrantAqua: 'linear-gradient(90deg, #00D2FF 0%, #3A7BD5 100%)',
  cosmicPurple: 'linear-gradient(180deg, #8E2DE2 0%, #4A00E0 100%)',
  actionOrange: 'linear-gradient(90deg, #FF8C00 0%, #FF4500 100%)',
  borderSubtle: 'rgba(255, 255, 255, 0.08)',
  textHigh: '#FFFFFF',
  textMedium: '#94A3B8',
  textMuted: '#475569'
};
